export const countriesData = [
    { id: 1, name: "Armenia", checked: false }, 
    { id: 2, name: "Russia", checked: false }, 
    { id: 3, name: "Poland", checked: false }, 
    { id: 4, name: "France", checked: false }, 
    { id: 5, name: "German", checked: false }, 
    { id: 6, name: "Aruba", checked: false }, 
    { id: 7, name: "Afghanistan", checked: false }, 
    { id: 8, name: "Angola", checked: false }, 
    { id: 9, name: "Albania", checked: false }, 
    { id: 10, name: "Andorra", checked: false }, 
    { id: 11, name: "United Arab Emirates", checked: false }, 
    { id: 12, name: "Argentina", checked: false }, 
    { id: 13, name: "American Samoa", checked: false }, 
    { id: 14, name: "Antigua and Barbuda", checked: false }, 
    { id: 15, name: "Australia", checked: false }, 
    { id: 16, name: "Burundi", checked: false }, 
    { id: 17, name: "Belgium", checked: false }, 
    { id: 18, name: "Bangladesh", checked: false }, 
    { id: 19, name: "Benin", checked: false }, 
    { id: 20, name: "Bulgaria", checked: false }, 
    { id: 21, name: "Belarus", checked: false }, 
    { id: 22, name: "Herzegovina", checked: false }, 
    { id: 23, name: "Belize", checked: false }, 
    { id: 24, name: "Bermuda", checked: false }, 
    { id: 25, name: "Bolivia", checked: false }, 
    { id: 26, name: "Bermuda", checked: false }, 
    { id: 27, name: "Canada", checked: false }, 
    { id: 28, name: "Switzerland", checked: false }, 
    { id: 29, name: "Bhutan", checked: false }, 
    { id: 30, name: "Chile", checked: false }
];

