export const countriesData = [
    { capital: "Yerevan", description: "Armenia, country of Transcaucasia, lying just south of the great mountain range of the Caucasus and fronting the northwestern extremity of Asia. To the north and east Armenia is bounded by Georgia and Azerbaijan, while its neighbours to the southeast and west are, respectively, Iran and Turkey. Naxçıvan, an exclave of Azerbaijan, borders Armenia to the southwest", id: 1, name: "Armenia", checked: false }, 
    { capital: "", description: "", id: 2, name: "Russia", checked: false }, 
    { capital: "", description: "", id: 3, name: "Poland", checked: false }, 
    { capital: "", description: "", id: 4, name: "France", checked: false }, 
    { capital: "", description: "", id: 5, name: "German", checked: false }, 
    { capital: "", description: "", id: 6, name: "Aruba", checked: false }, 
    { capital: "", description: "", id: 7, name: "Afghanistan", checked: false }, 
    { capital: "", description: "", id: 8, name: "Angola", checked: false }, 
    { capital: "", description: "", id: 9, name: "Albania", checked: false }, 
    { capital: "", description: "", id: 10, name: "Andorra", checked: false }, 
    { capital: "", description: "", id: 11, name: "United Arab Emirates", checked: false }, 
    { capital: "", description: "", id: 12, name: "Argentina", checked: false }, 
    { capital: "", description: "", id: 13, name: "American Samoa", checked: false }, 
    { capital: "", description: "", id: 14, name: "Antigua and Barbuda", checked: false }, 
    { capital: "", description: "", id: 15, name: "Australia", checked: false }, 
    { capital: "", description: "", id: 16, name: "Burundi", checked: false }, 
    { capital: "", description: "", id: 17, name: "Belgium", checked: false }, 
    { capital: "", description: "", id: 18, name: "Bangladesh", checked: false }, 
    { capital: "", description: "", id: 19, name: "Benin", checked: false }, 
    { capital: "", description: "", id: 20, name: "Bulgaria", checked: false }, 
    { capital: "", description: "", id: 21, name: "Belarus", checked: false }, 
    { capital: "", description: "", id: 22, name: "Herzegovina", checked: false }, 
    { capital: "", description: "", id: 23, name: "Belize", checked: false }, 
    { capital: "", description: "", id: 24, name: "Bermuda", checked: false }, 
    { capital: "", description: "", id: 25, name: "Bolivia", checked: false }, 
    { capital: "", description: "", id: 26, name: "Bermuda", checked: false }, 
    { capital: "", description: "", id: 27, name: "Canada", checked: false }, 
    { capital: "", description: "", id: 28, name: "Switzerland", checked: false }, 
    { capital: "", description: "", id: 29, name: "Bhutan", checked: false }, 
    { capital: "", description: "", id: 30, name: "Chile", checked: false }
];

