export const countriesArray = [
    { id: 1, name: "Armenia", isCheck: false }, 
    { id: 2, name: "Russia", isCheck: false }, 
    { id: 3, name: "Poland", isCheck: false }, 
    { id: 4, name: "France", isCheck: false }, 
    { id: 5, name: "German", isCheck: false }, 
    { id: 6, name: "Aruba", isCheck: false }, 
    { id: 7, name: "Afghanistan", isCheck: false }, 
    { id: 8, name: "Angola", isCheck: false }, 
    { id: 9, name: "Albania", isCheck: false }, 
    { id: 10, name: "Andorra", isCheck: false }, 
    { id: 11, name: "United Arab Emirates", isCheck: false }, 
    { id: 12, name: "Argentina", isCheck: false }, 
    { id: 13, name: "American Samoa", isCheck: false }, 
    { id: 14, name: "Antigua and Barbuda", isCheck: false }, 
    { id: 15, name: "Australia", isCheck: false }, 
    { id: 16, name: "Burundi", isCheck: false }, 
    { id: 17, name: "Belgium", isCheck: false }, 
    { id: 18, name: "Bangladesh", isCheck: false }, 
    { id: 19, name: "Benin", isCheck: false }, 
    { id: 20, name: "Bulgaria", isCheck: false }, 
    { id: 21, name: "Belarus", isCheck: false }, 
    { id: 22, name: "Bosnia and Herzegovina", isCheck: false }, 
    { id: 23, name: "Belize", isCheck: false }, 
    { id: 24, name: "Bermuda", isCheck: false }, 
    { id: 25, name: "Bolivia", isCheck: false }, 
    { id: 26, name: "Bermuda", isCheck: false }, 
    { id: 27, name: "Canada", isCheck: false }, 
    { id: 28, name: "Switzerland", isCheck: false }, 
    { id: 29, name: "Bhutan", isCheck: false }, 
    { id: 30, name: "Chile", isCheck: false }
];